# Generated by Django 4.0.4 on 2023-09-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate', models.CharField(choices=[('hot', 'Hot'), ('humid', 'Humid'), ('rainy', 'Rainy'), ('cold', 'Cold')], max_length=5)),
                ('area_code', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('chances_of_rain', models.FloatField()),
            ],
        ),
    ]
